### ISSUE TITLE
Error viewing logs

### ISSUE THREAD

**Issue by riahc3** [jamesbrindle/YTMusicUploader#17]
I was gonna post that YTMusicUploader discovers a lot of songs but only uploads 144 but I cant even view the logs to give more info.

I view the logs and get this error:

************** Exception Text **************
System.AggregateException: One or more errors occurred. ---> System.Data.DataException: Error parsing column 10 (LastUploadError=1 - Decimal) ---> System.InvalidCastException: Invalid cast from 'Decimal' to 'DateTime'.
   at System.Decimal.System.IConvertible.ToDateTime(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Deserializee1d7b685-4d84-42ca-a4ae-ebb885f820d5(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3634
   at Deserializee1d7b685-4d84-42ca-a4ae-ebb885f820d5(IDataReader )
   at Dapper.SqlMapper.<QueryImpl>d__140`1.MoveNext() in /_/Dapper/SqlMapper.cs:line 1098
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 721
   at YTMusicUploader.Providers.Repos.MusicFileRepo.<LoadUploaded_R>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YTMusicUploader.Providers.Repos.MusicFileRepo.<LoadUploaded>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at YTMusicUploader.Dialogues.UploadLog.PbRefresh_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.Data.DataException: Error parsing column 10 (LastUploadError=1 - Decimal) ---> System.InvalidCastException: Invalid cast from 'Decimal' to 'DateTime'.
   at System.Decimal.System.IConvertible.ToDateTime(IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Deserializee1d7b685-4d84-42ca-a4ae-ebb885f820d5(IDataReader )
   --- End of inner exception stack trace ---
   at Dapper.SqlMapper.ThrowDataException(Exception ex, Int32 index, IDataReader reader, Object value) in /_/Dapper/SqlMapper.cs:line 3634
   at Deserializee1d7b685-4d84-42ca-a4ae-ebb885f820d5(IDataReader )
   at Dapper.SqlMapper.<QueryImpl>d__140`1.MoveNext() in /_/Dapper/SqlMapper.cs:line 1098
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dapper.SqlMapper.Query[T](IDbConnection cnn, String sql, Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) in /_/Dapper/SqlMapper.cs:line 721
   at YTMusicUploader.Providers.Repos.MusicFileRepo.<LoadUploaded_R>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at YTMusicUploader.Providers.Repos.MusicFileRepo.<LoadUploaded>d__16.MoveNext()<---

VM is in English US.

**Comment by jamesbrindle** [comment]
Hey,

This is an odd one... It looks as though the database is out of sync with the version of the app (despite during installation, the database should be automatically updated anyway, but may have got corrupted somehow)... Did you 'upgrade' the application from 1.5.2(or below) -> 1.5.3? Or have you installed 1.5.3 without installing any prior versions?

If it's the former, could you try uninstalling the YTM app, and completely delete this folder:

%localappdata%\YTMusicUploader

And then see if installing version 1.5.3 fixes the issue?

**Comment by jamesbrindle** [comment]
No response, no other reports - Assuming fixed
