### ISSUE TITLE
Not every Song is added to playlist / playlist not created at all

### ISSUE THREAD

**Issue by LeSnowTiger** [jamesbrindle/YTMusicUploader#21]
Hi 

I've have some issues about the playlists.
I tried to one playlist with about 2k files. The playlist was created but only 49 Songs were added.

After this i tried it only with some songs. This time the playlist was not created at all. (tried different formats aswell)

I'm really not sure what I'm doing wrong. 

Regards, 
LeSnowTiger

**Comment by jamesbrindle** [comment]
Hey,

I'm not sure what's going on with the playlists... I'm looking into it at present, there are a couple of issues it seems.

Regards,

J

**Comment by LeSnowTiger** [comment]
No Problem. Let me know if you need anything!

**Comment by Cowtownchina** [comment]
Hello,

Big props to you James on creating this awesome Uploader app! Makes managing my music between YT and my iTunes so much easier!

I also am having issues where the playlist being uploaded don't have all the songs. Appreciate you looking into that issue and I am happy to help test or provide you any info that will help you out.

Thanks.
CowtownChina

**Comment by jamesbrindle** [comment]
Hey guys,

I will certainly have a look at this as soon as I can. I've got a big systems upgrade going on at my actual job this weekend so I'm a bit short on time.

In the meantime, if you don't mind, would you be able to put a copy of your playlists file(s) here:

https://1drv.ms/u/s!At6EvCXZJAN60q1k9T-CoPMACw7Kpw?e=TTPq4q

Also, what would be helpful is to keep the 'Send Diagnostic Data' enabled, so I can check the logs... I am aware of issues songs not adding to current playlists, and playlists not creating at all... The error information I'm getting from YTM are basically useless, so it's a bit of trial and error trying to troubleshoot but I will get there.

Regards,

J

**Comment by Cowtownchina** [comment]
Hey James,

No rush. Appreciate you taking the time to look at these issues. I uploaded my playlist files to your one drive. I also do have "Send Diagnostic Data" turned on. I never turned it off.

Thanks,
CowtownChina

**Comment by jamesbrindle** [comment]
Well, after spending a couple of hours trying to figure out what the issue was, I have determined that I'm using the correct 'videoIds' that YouTube / YouTube Music uses, and verified I'm create the request JSON properly...

Turns out though, that the site limits the amount of playlists created in a short amount of time to 10, and will then block subsequent playlists being created for 24 hours!

You can't even do this on the official site:

[![N|Solid](https://portfolio.jb-net.co.uk/shared/ytmusic-playlisterror.png)](https://github.com/jamesbrindle/YTMusicUploader)
&nbsp;

I believe this stems from other third parties trying to do something similar to what I'm doing and 'synching up' playlists over different platforms (like 'Spotify' to YTM').

What I'm going to do is implement a 'wait' mechanism... Waiting 10 seconds before each 'create playlists' and 2 seconds for each 'add to existing playlist'.... and see if that somehow works...

This may take a while to upload playlists consisting of many songs just to be aware, but if works around the issue it may be worth it.

**Comment by Cowtownchina** [comment]
Thanks for the update James. Yeah uploading playlists to YTM definitely isn't the easiest thing in my experience. It would be awesome if you could get that going. I wouldn't care how long it takes, as long as it would finally just upload properly.

Thanks!

**Comment by furiousjay** [comment]
Hello! In my case there are no Playlists imported into YTMusic Uploader. They are saved as m3u files within the Music Folder but the YTMusic Upload Manager shows no Playlists at all. Do I make something wrong?

**Comment by jamesbrindle** [comment]
Hey,

The YT Music Uploader - YTM Manager shows whatever is on YouTube music, not your hard drive (sorry if that's obvious I wasn't sure by the description).

The YT Music Uploader will process playlists at the end - As the last process after it's scanned your hard drive and uploaded everything, as the music files needs to be uploaded and present in YTM, and won't create empty playlists... There can be a small delay between uploading your music, to it being visible on a YTM (a minute - I don't think that will be an issue unless you only have 1 playlists of the last uploaded album).

Other than that - So long as you've got the 'Upload Playlists' option checked, and the file paths inside your .m3u point to actual files and the links haven't been broken, it should work?

Also, I need to mention - For some odd reason - Which I think stems from YouTube rather than YTM, YouTube has a policy of only being able to create 25 playlists per day automatically... I do not know why, but I'm unable to get around this.

Are 'any' playlists present on YTM Manger? Or do you have 0?

**Comment by furiousjay** [comment]
Oh! I indeed did not understand correctly that the Manager shows the YT Music content. Anyway I synced all my music now successfully. Each folder contains an .m3u file with a playlist of all the songs in the folder. The Playlist-Files should be correct, as they can be opened in VLC Player. All my music tracks are now synced but there are no Playlists on YT Music

 I also created one playlist to check on YT Music to see if it is synced in the manager, but it was not... Do you have any further advices? 

![playlist not synced](https://user-images.githubusercontent.com/38959383/116887545-b9c17780-ac2a-11eb-9177-4d642c8e651e.PNG)
![playlist not synced2](https://user-images.githubusercontent.com/38959383/116887558-bcbc6800-ac2a-11eb-94eb-4b8a8bcbb5fb.PNG)

Also I want to say THANK YOU for making this tool and answering the questions. Really great job!

**Comment by jamesbrindle** [comment]
Hmm... That is very bizarre.

1. You should see your playlist if it's on YTM - Could you try clicking the refresh button (top left in Manage YT Music - to re-fetch the entire list).

2. Please could you put one or two of your playlists here so I can give them a once over: https://1drv.ms/u/s!At6EvCXZJAN61dVCYkJy9jWfJ9xZCw?e=MfHH9d

3. Is there anything mentioned in the application log (click the 'Log' icon button to the left of the 'Manage YT Music Button').

I've also noticed, the YTM Uploader UI is a little distorted for you, probably because of increased dpi fonts (like 125% / 150%) - I'll fix that!

Regards,

Jamie

**Comment by furiousjay** [comment]
Alright. Maybe it is just a bug that only me is facing. Idk

1. I pressed the Reset-Button on the left. The recheck gives the same output.
2. I uploaded two of the m3u Playlists. I hope that is what you were asking for.
3. In the log there are no Errors, Warnings or Criticals. If I go to "all" I see the uploads of the mp3 files. But I saw not a single log entry for m3u playlists.

Regaring the upload location: This is because my Windows is German. I think Windows shows the german word "Musik" in the explorer while the path is still with "music". I moved the folder to the root of C:/ to avoid any errors by that. The Log shows that the files are moved and updates the path. But the playlists are still not uploaded. 

Regaring the resolution I have a 1080p Monitor with 125% Scaling. If I open the Manager it shows an error message which I clicked away with "continue". This is the content of the message:


See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: targetBounds
   at System.Windows.Forms.Control.DrawToBitmap(Bitmap bitmap, Rectangle targetBounds)
   at JBToolkit.ColourHelper.MakeTransparent(Control control, Graphics g)
   at JBToolkit.WinForms.RoundTextBox.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
YTMusicUploader
    Assembly Version: 1.7.4.0
    Win32 Version: 1.7.4
    CodeBase: file:///C:/Program%20Files/JB-Net%20Software%20Solutions/YT%20Music%20Uploader/YTMusicUploader.exe
----------------------------------------
MetroFramework
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///C:/Program%20Files/JB-Net%20Software%20Solutions/YT%20Music%20Uploader/MetroFramework.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ServiceModel.Channels
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C


CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Channels/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Channels.dll
----------------------------------------
System.ServiceModel.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Web/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Web.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.IdentityModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
Ookii.Dialogs.WinForms
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/JB-Net%20Software%20Solutions/YT%20Music%20Uploader/Ookii.Dialogs.WinForms.DLL
----------------------------------------
MetroFramework.Fonts
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///C:/Program%20Files/JB-Net%20Software%20Solutions/YT%20Music%20Uploader/MetroFramework.Fonts.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Data.HashFunction.xxHash
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Program%20Files/JB-Net%20Software%20Solutions/YT%20Music%20Uploader/System.Data.HashFunction.xxHash.DLL
----------------------------------------
System.Data.HashFunction.Interfaces
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Program%20Files/JB-Net%20Software%20Solutions/YT%20Music%20Uploader/System.Data.HashFunction.Interfaces.DLL
----------------------------------------
System.Data.HashFunction.Core
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/Program%20Files/JB-Net%20Software%20Solutions/YT%20Music%20Uploader/System.Data.HashFunction.Core.DLL
----------------------------------------
Microsoft.Web.WebView2.WinForms
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/JB-Net%20Software%20Solutions/YT%20Music%20Uploader/Microsoft.Web.WebView2.WinForms.DLL
----------------------------------------
Microsoft.Web.WebView2.Core
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Program%20Files/JB-Net%20Software%20Solutions/YT%20Music%20Uploader/Microsoft.Web.WebView2.Core.DLL
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
System.Data.SQLite
    Assembly Version: 1.0.113.0
    Win32 Version: 1.0.113.0
    CodeBase: file:///C:/Program%20Files/JB-Net%20Software%20Solutions/YT%20Music%20Uploader/System.Data.SQLite.DLL
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1

CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
Dapper
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.35.21366
    CodeBase: file:///C:/Program%20Files/JB-Net%20Software%20Solutions/YT%20Music%20Uploader/Dapper.DLL
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Program%20Files/JB-Net%20Software%20Solutions/YT%20Music%20Uploader/Newtonsoft.Json.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Octokit
    Assembly Version: 0.48.0.0
    Win32 Version: 0.48.0.0
    CodeBase: file:///C:/Program%20Files/JB-Net%20Software%20Solutions/YT%20Music%20Uploader/Octokit.DLL
----------------------------------------
Brotli.Core
    Assembly Version: 2.0.4.2
    Win32 Version: 2.0.4.2
    CodeBase: file:///C:/Program%20Files/JB-Net%20Software%20Solutions/YT%20Music%20Uploader/Brotli.Core.DLL
----------------------------------------
System.Runtime.InteropServices.RuntimeInformation
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.InteropServices.RuntimeInformation/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.InteropServices.RuntimeInformation.dll
----------------------------------------
TagLibSharp
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0.0
    CodeBase: file:///C:/Program%20Files/JB-Net%20Software%20Solutions/YT%20Music%20Uploader/TagLibSharp.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:


<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by jamesbrindle** [comment]
Hey,

I haven't necessarily fixed the issue with the playlists not uploading but I have come across your error logs in the diagnostic data sent and have manage to narrow down where the issue is happening - It is a bug. You're getting an 'Object reference not set to an instance of an object' exception in the main loop of the playlist processor.

I've added additional logging in that area to hopefully further narrow down the issue and fix it:

https://github.com/jamesbrindle/YTMusicUploader/releases/tag/v1.7.6

Regards,

J

**Comment by furiousjay** [comment]
Thank you very much for the efforts to solve this issue! 
I tried your latest version. Great Work! The scaling has been fixed. Also for the first time the programm showed "processing playlists". Now some of my playlists were uploaded more than once. Some Playlists were not uploaded at all. I guess this was because I tried to create several playlist files with absolute and relative paths and now the Uploader has reached the limit of 10 Playlists. I will try again in 1-2 days to see if it then uploads the rest of the playlists and give feedback. 
By they way... Can I offer you some small donation for creating this software? I really appreciate your work and would be happy if  your next drink is on me ;-).

**Comment by jamesbrindle** [comment]
Hey,

Cool, yep, I'll keep an eye on the logs.

You're more than welcome to buy me a coffee:

https://www.buymeacoffee.com/jamiebrindle

Thanks!

Regards,

J

**Comment by Cowtownchina** [comment]
Hey James,

I just downloaded the latest version today and deleted all my playlists I
wanted to upload on YTM to see how it would go with the new version. I
confirmed from the logs that I am also getting the "'Object reference not
set to an instance of an object' error.

I'm with FuriusJay in saying thank you for taking the time to look at these
issues and your awesome work on releasing new versions of the Uploader!
I'll be buying you a coffee as well!

Thanks!
CowtownChina

**Comment by jamesbrindle** [comment]
Thanks for the coffee!

Any chance you could put a copy of your database here:

https://1drv.ms/u/s!At6EvCXZJAN61dVCYkJy9jWfJ9xZCw?e=MfHH9d

The database is by default in this location:

C:\Users\jamie\AppData\Local\YTMusicUploader\ytuploader.db

or if installed 'All Users':

c:\ProgramData\YTMusicUploader

Something just isn't quite right and I'm having a tough time pinpointing the error.

**Comment by Cowtownchina** [comment]
You are welcome.

That link for OneDrive doesn't work for me. Is there another link I can
upload a copy of my database to?

Thanks,
Dan

**Comment by Cowtownchina** [comment]
Great. It is uploaded now.

Thanks,
Dan

**Comment by branches78** [comment]
I don't know if you guys already know this but playlists where songs begging with three dots won't be recognized by YouTube Music Uploader, the playlist must contain the full path of the song in order for it to work, for example;

Incorrect:

...\Music\songfilename.mp3

Correct:

D:\Music\songfilename.mp3

**Comment by branches78** [comment]
I also found out that it's not creating the playlists with the songs in the same order within the playlist but it scrambles all the songs altogether.
